<a href="https://colab.research.google.com/github/mirpouya/TensorFlow-Tutorial/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(5)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=5>

as you can see it has no shape

In [ ]:
tensor_one_d = tf.constant([1, 2, 3])
tensor_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [11, 22, 33, 44]
])

tensor_two_d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [11, 22, 33, 44]], dtype=int32)>

In [ ]:
tensor_three_d = tf.constant([
    [
        [1, 2, 3, 4],
        [11, 22, 33, 44],
        [111, 222, 333, 444]
    ],

    [
        [-1, -2, -3, -4],
        [-11, -22, -33, -44],
        [-111, -222, -333, -444]
    ]
])

tensor_three_d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[   1,    2,    3,    4],
        [  11,   22,   33,   44],
        [ 111,  222,  333,  444]],

       [[  -1,   -2,   -3,   -4],
        [ -11,  -22,  -33,  -44],
        [-111, -222, -333, -444]]], dtype=int32)>

In [ ]:
tensor_zero_d.ndim, tensor_one_d.ndim, tensor_two_d.ndim, tensor_three_d.ndim

(0, 1, 2, 3)

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1, 2, 3, 4])
np_array

array([1, 2, 3, 4])

In [ ]:
np_array.shape

(4,)

In [ ]:
# convert to tensor
tf_array = tf.convert_to_tensor(np_array)
tf_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns= 4,
    dtype = tf.float32,
    name = "bababa"
)

eye_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [ ]:
# fill method

fill_tensor = tf.fill(
    [2, 3, 4], 3
)

fill_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]], dtype=int32)>

In [ ]:
# ones_like method

ones_like_tensor = tf.ones_like(
    fill_tensor
)

ones_like_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [ ]:
ones_like_tensor.shape, tf.size(ones_like_tensor)

(TensorShape([2, 3, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
# normal random tensor

normal_random_tensor = tf.random.normal(
    [2, 3],
    mean = 0.0,
    stddev = 1.0,
    seed = None,
    name = None
)

normal_random_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.98761696, -0.9384622 , -1.2105776 ],
       [ 1.1914092 , -1.5789397 , -0.4133352 ]], dtype=float32)>

<h2> Tensor Indexing </b>

In [ ]:
tf_tensor = tf.constant([2, 20, 200, 2000, 20000])
tf_tensor[0: 4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   2,   20,  200, 2000], dtype=int32)>

In [ ]:
tf_tensor[0: 4: 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  2, 200], dtype=int32)>

In [ ]:
tf_2d_tensor = tf.reshape(tf.range(1, 24+1), [4, 6])
tf_2d_tensor

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
# indexing
tf_2d_tensor[1:3, 2: 5]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 10, 11],
       [15, 16, 17]], dtype=int32)>

In [ ]:
# getting 23 in the 4th row and 5th column
tf_2d_tensor[3, 4]

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [ ]:
# picking every row, or any dimension
tf_2d_tensor[..., 3]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4, 10, 16, 22], dtype=int32)>

In [ ]:
# 2d tensor indexing

tf_3d_tensor = tf.reshape(tf.range(1, 30+1), [3, 5, 2])
tf_3d_tensor

<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]], dtype=int32)>

In [ ]:
tf_3d_tensor[1:4, 0:2, 0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [21, 23]], dtype=int32)>

In [ ]:
tf_3d_tensor[1:4, 0:2, ...]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
tf_3d_tensor[0, :, :]

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>

<h2> Matrix Multiplication <h2>

In [ ]:
tensor_1 = tf.constant([1, 2, 3, 4])
tensor_2 = tf.constant([[10], [11], [13], [14], [15]])


print(tensor_1.shape)
print(tensor_2.shape)
multiply_tensors = tf.math.multiply(tensor_1, tensor_2)

print(multiply_tensors)

(4,)
(5, 1)
tf.Tensor(
[[10 20 30 40]
 [11 22 33 44]
 [13 26 39 52]
 [14 28 42 56]
 [15 30 45 60]], shape=(5, 4), dtype=int32)


In [ ]:
tf_2d_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

tf.math.reduce_sum(
    tf_2d_tensor, axis=0, keepdims=True, name=None
)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[22, 26, 30]], dtype=int32)>

In [ ]:
tf.math.reduce_sum(
    tf_2d_tensor, axis=0, keepdims=False, name=None
)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 26, 30], dtype=int32)>

In [ ]:
tf.math.reduce_sum(
    tf_2d_tensor, axis=1, keepdims=False, name=None
)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6, 15, 24, 33], dtype=int32)>

<h1><b> Linear Algebra </b></h1>

<b> Matrix Multiplication </b>

In [ ]:
tensor_1 = tf.constant([[1, 2, 3],
                        [5, 6, 7]])
tensor_2 = tf.constant([[3, 3, 3],
                        [-2, -3, -4]])

product = tf.linalg.matmul(
    tensor_1, tensor_2, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

InvalidArgumentError: ignored

In [ ]:
print(f"tensor_1 shape: {tensor_1.shape}")
print(f"tensor_2 shape: {tensor_2.shape}")

tensor_1 shape: (2, 3)
tensor_2 shape: (2, 3)


In [ ]:
product = tf.linalg.matmul(
    tensor_1, tensor_2, transpose_a=False, transpose_b=True, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

In [ ]:
product.shape, product

(TensorShape([2, 2]),
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 18, -20],
        [ 54, -56]], dtype=int32)>)

In [ ]:
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7]], dtype=int32)>

In [ ]:
# another way of matrix multiplication

tensor_1 @ tf.transpose(tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 18, -20],
       [ 54, -56]], dtype=int32)>

In [ ]:
x_1 = tf.random.uniform(
    [2,3],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

x_2 = tf.random.uniform(
    [3,4],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

x_3 = tf.random.uniform(
    [4,5],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [ ]:
(x_1 @ x_2 @ x_3).shape

TensorShape([2, 5])

In [ ]:
x_1 = tf.random.uniform(
    [2, 3, 4],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

x_2 = tf.random.uniform(
    [2, 4, 2],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [ ]:
x_1 @ x_2

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1.2304939 , 1.0299494 ],
        [0.8149803 , 0.6797341 ],
        [1.3120302 , 1.2020078 ]],

       [[0.32055235, 1.1040404 ],
        [0.80676955, 1.6644917 ],
        [0.34881267, 1.2876651 ]]], dtype=float32)>

In [ ]:
(x_1 @ x_2).shape

TensorShape([2, 3, 2])

In [ ]:
# is it possible to multiply a 3d tensor with a 2d tensor?

x_1 = tf.random.uniform(
    [2, 3],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

x_2 = tf.random.uniform(
    [4, 3, 5],
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [ ]:
x_1 @ x_2

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[0.33638567, 0.63433087, 0.1128162 , 0.5556294 , 0.491733  ],
        [0.18587816, 0.4773082 , 0.0947867 , 0.2475264 , 0.20004046]],

       [[0.7121585 , 0.6943798 , 0.81744134, 0.4906497 , 0.9197161 ],
        [0.44105485, 0.40627646, 0.44987795, 0.3521564 , 0.5846714 ]],

       [[0.47924432, 0.8588759 , 0.24295114, 0.46851277, 0.4641593 ],
        [0.31703067, 0.48524636, 0.11530998, 0.35309565, 0.37601745]],

       [[0.71813786, 0.5179974 , 0.86664927, 0.493598  , 0.32230896],
        [0.45796338, 0.4023732 , 0.5139823 , 0.28019422, 0.19269913]]],
      dtype=float32)>

In [ ]:
(x_1 @ x_2).shape

TensorShape([4, 2, 5])

<b> inverse matrix <b>

In [ ]:
tensor_1 = tf.random.normal(
    [3, 3],
    mean = 0.0,
    stddev = 1.0,
    seed = None,
    name = None
)

tensor_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.6031239 ,  2.1899347 ,  1.5143416 ],
       [-1.425258  , -0.01092726, -0.9364687 ],
       [-0.5277227 ,  1.4665722 ,  0.20582134]], dtype=float32)>

In [ ]:
tf.linalg.inv(tensor_1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.60233825, -0.77761936,  0.8936378 ],
       [-0.34596363, -0.29653096,  1.1962572 ],
       [ 0.9207653 ,  0.11911619, -1.3740301 ]], dtype=float32)>

In [ ]:
tensor_1 @ tf.linalg.inv(tensor_1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.00000000e+00, -1.59131552e-09, -7.96330824e-09],
       [-3.24316574e-08,  9.99999821e-01, -2.79557071e-08],
       [ 1.11922866e-07,  1.21255699e-08,  9.99999762e-01]], dtype=float32)>

<b> singular value desomposition </b>

In [ ]:
tensor_1 = tf.random.uniform(
    [3, 5],
    minval = 1,
    maxval = 10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

tensor_1

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[4.2488556, 1.2026902, 7.565465 , 5.038923 , 1.1599905],
       [5.4781914, 9.696188 , 1.0995765, 9.303658 , 9.509663 ],
       [8.70355  , 9.931801 , 2.668067 , 6.157505 , 6.0603876]],
      dtype=float32)>

In [ ]:
tf.linalg.svd(tensor_1)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([24.223114 ,  7.817013 ,  3.7401106], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.29108658,  0.932279  , -0.21476567],
        [-0.70180947, -0.36064696, -0.61432654],
        [-0.6501785 , -0.02809763,  0.7592617 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[-0.44339028,  0.22270359,  0.62307435],
        [-0.5619593 , -0.33960757,  0.35451204],
        [-0.19438533,  0.8419582 , -0.07340427],
        [-0.49537948,  0.14958847, -0.56749994],
        [-0.45212856, -0.32217905, -0.3983154 ]], dtype=float32)>)

In [ ]:
s, u, v = tf.linalg.svd(tensor_1)

print(f" s: {s}\n\n u: {u}\n\n v: {v}\n\n")

 s: [24.223114   7.817013   3.7401106]

 u: [[-0.29108658  0.932279   -0.21476567]
 [-0.70180947 -0.36064696 -0.61432654]
 [-0.6501785  -0.02809763  0.7592617 ]]

 v: [[-0.44339028  0.22270359  0.62307435]
 [-0.5619593  -0.33960757  0.35451204]
 [-0.19438533  0.8419582  -0.07340427]
 [-0.49537948  0.14958847 -0.56749994]
 [-0.45212856 -0.32217905 -0.3983154 ]]


