<a href="https://colab.research.google.com/github/mirpouya/TensorFlow-Tutorial/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(5)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=5>

as you can see it has no shape

In [3]:
tensor_one_d = tf.constant([1, 2, 3])
tensor_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
tensor_two_d = tf.constant([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [11, 22, 33, 44]
])

tensor_two_d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [11, 22, 33, 44]], dtype=int32)>

In [8]:
tensor_three_d = tf.constant([
    [
        [1, 2, 3, 4],
        [11, 22, 33, 44],
        [111, 222, 333, 444]
    ],

    [
        [-1, -2, -3, -4],
        [-11, -22, -33, -44],
        [-111, -222, -333, -444]
    ]
])

tensor_three_d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[   1,    2,    3,    4],
        [  11,   22,   33,   44],
        [ 111,  222,  333,  444]],

       [[  -1,   -2,   -3,   -4],
        [ -11,  -22,  -33,  -44],
        [-111, -222, -333, -444]]], dtype=int32)>

In [10]:
tensor_zero_d.ndim, tensor_one_d.ndim, tensor_two_d.ndim, tensor_three_d.ndim

(0, 1, 2, 3)

In [11]:
import numpy as np

In [14]:
np_array = np.array([1, 2, 3, 4])
np_array

array([1, 2, 3, 4])

In [15]:
np_array.shape

(4,)

In [16]:
# convert to tensor
tf_array = tf.convert_to_tensor(np_array)
tf_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [18]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns= 4,
    dtype = tf.float32,
    name = "bababa"
)

eye_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [21]:
# fill method

fill_tensor = tf.fill(
    [2, 3, 4], 3
)

fill_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]], dtype=int32)>

In [22]:
# ones_like method

ones_like_tensor = tf.ones_like(
    fill_tensor
)

ones_like_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [25]:
ones_like_tensor.shape, tf.size(ones_like_tensor)

(TensorShape([2, 3, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [27]:
# normal random tensor

normal_random_tensor = tf.random.normal(
    [2, 3],
    mean = 0.0,
    stddev = 1.0,
    seed = None,
    name = None
)

normal_random_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.33867437,  1.2658099 ,  0.51056135],
       [ 0.04571918,  0.04542223,  0.9992742 ]], dtype=float32)>