<a href="https://colab.research.google.com/github/mirpouya/TensorFlow-Tutorial/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(5)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=5>

as you can see it has no shape

In [3]:
tensor_one_d = tf.constant([1, 2, 3])
tensor_one_d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
tensor_two_d = tf.constant([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [11, 22, 33, 44]
])

tensor_two_d

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [11, 22, 33, 44]], dtype=int32)>

In [5]:
tensor_three_d = tf.constant([
    [
        [1, 2, 3, 4],
        [11, 22, 33, 44],
        [111, 222, 333, 444]
    ],

    [
        [-1, -2, -3, -4],
        [-11, -22, -33, -44],
        [-111, -222, -333, -444]
    ]
])

tensor_three_d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[   1,    2,    3,    4],
        [  11,   22,   33,   44],
        [ 111,  222,  333,  444]],

       [[  -1,   -2,   -3,   -4],
        [ -11,  -22,  -33,  -44],
        [-111, -222, -333, -444]]], dtype=int32)>

In [6]:
tensor_zero_d.ndim, tensor_one_d.ndim, tensor_two_d.ndim, tensor_three_d.ndim

(0, 1, 2, 3)

In [7]:
import numpy as np

In [8]:
np_array = np.array([1, 2, 3, 4])
np_array

array([1, 2, 3, 4])

In [9]:
np_array.shape

(4,)

In [10]:
# convert to tensor
tf_array = tf.convert_to_tensor(np_array)
tf_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [11]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns= 4,
    dtype = tf.float32,
    name = "bababa"
)

eye_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [12]:
# fill method

fill_tensor = tf.fill(
    [2, 3, 4], 3
)

fill_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]],

       [[3, 3, 3, 3],
        [3, 3, 3, 3],
        [3, 3, 3, 3]]], dtype=int32)>

In [13]:
# ones_like method

ones_like_tensor = tf.ones_like(
    fill_tensor
)

ones_like_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

In [14]:
ones_like_tensor.shape, tf.size(ones_like_tensor)

(TensorShape([2, 3, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [15]:
# normal random tensor

normal_random_tensor = tf.random.normal(
    [2, 3],
    mean = 0.0,
    stddev = 1.0,
    seed = None,
    name = None
)

normal_random_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.3742578 , -0.21827085,  0.07731324],
       [ 0.79761374, -0.11740932, -1.8225725 ]], dtype=float32)>

<h2> Tensor Indexing </b>

In [16]:
tf_tensor = tf.constant([2, 20, 200, 2000, 20000])
tf_tensor[0: 4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   2,   20,  200, 2000], dtype=int32)>

In [17]:
tf_tensor[0: 4: 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  2, 200], dtype=int32)>

In [32]:
tf_2d_tensor = tf.reshape(tf.range(1, 24+1), [4, 6])
tf_2d_tensor

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]], dtype=int32)>

In [33]:
# indexing
tf_2d_tensor[1:3, 2: 5]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 10, 11],
       [15, 16, 17]], dtype=int32)>

In [39]:
# getting 23 in the 4th row and 5th column
tf_2d_tensor[3, 4]

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [40]:
# picking every row, or any dimension
tf_2d_tensor[..., 3]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4, 10, 16, 22], dtype=int32)>

In [41]:
# 2d tensor indexing

tf_3d_tensor = tf.reshape(tf.range(1, 30+1), [3, 5, 2])
tf_3d_tensor

<tf.Tensor: shape=(3, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]], dtype=int32)>

In [42]:
tf_3d_tensor[1:4, 0:2, 0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [21, 23]], dtype=int32)>

In [43]:
tf_3d_tensor[1:4, 0:2, ...]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 12],
        [13, 14]],

       [[21, 22],
        [23, 24]]], dtype=int32)>

In [45]:
tf_3d_tensor[0, :, :]

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>

<h2> Matrix Multiplication <h2>

In [52]:
tensor_1 = tf.constant([1, 2, 3, 4])
tensor_2 = tf.constant([[10], [11], [13], [14], [15]])


print(tensor_1.shape)
print(tensor_2.shape)
multiply_tensors = tf.math.multiply(tensor_1, tensor_2)

print(multiply_tensors)

(4,)
(5, 1)
tf.Tensor(
[[10 20 30 40]
 [11 22 33 44]
 [13 26 39 52]
 [14 28 42 56]
 [15 30 45 60]], shape=(5, 4), dtype=int32)


In [57]:
tf_2d_tensor = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]])

tf.math.reduce_sum(
    tf_2d_tensor, axis=0, keepdims=True, name=None
)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[22, 26, 30]], dtype=int32)>

In [59]:
tf.math.reduce_sum(
    tf_2d_tensor, axis=0, keepdims=False, name=None
)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22, 26, 30], dtype=int32)>

In [60]:
tf.math.reduce_sum(
    tf_2d_tensor, axis=1, keepdims=False, name=None
)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6, 15, 24, 33], dtype=int32)>